### ISSUE TITLE
zmq backend - adding a pool of connector

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/metlog-py#14]
The way the connectors are instantiated cannot work because each incoming request is a new thread, and the zmq connector created then is not freed, so you run out of fds on high loads and leak.

The best way to fix this is to use a thread-safe pool of connectors, where you can control the size

see : https://github.com/mozilla-services/powerhose/blob/master/powerhose/client.py#L82

I guess we could work on using the same pool

**Comment by rafrombrc** [comment]
Collaboration on pool implementation is welcome, but as a band-aid we've provided our own, it's included in the just-released 0.8.4.
